version: "3.9"

services:
  db:
    image: postgres:16
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: gobank
    ports:
      - "5432:5432"
    volumes:
      - ./deploy/postgres/data:/var/lib/postgresql/data
      - ./deploy/postgres/init:/docker-entrypoint-initdb.d
      - ./deploy/postgres/log:/var/log/post
